backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "action"
    label: "Action"
    folder: "src/pages/action"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Subheading", name: "subheading", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Embed markup (div tag)", name: "embed", widget: "text" }
      - { label: "Embed scripts (script tag)", name: "scripts", widget: "text" }
      - { label: "Before the jump", name: "before", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
